/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rookieintraining.nobel;

import com.rookieintraining.nobel.drivers.Driver;
import com.rookieintraining.nobel.factories.DriverFactory;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.OutputType;

import java.io.File;
import java.io.IOException;

class AppiumTest {

    @Test void someLibraryMethodReturnsTrue() throws IOException {
        Driver driver = DriverFactory.get();
        driver.get("https://www.google.com");

        System.out.println(driver.getTitle());

        File screenShot = driver.takeScreenshot(OutputType.FILE);
        File screenshotFile = new File(System.getProperty("user.dir") + "/sample.jpg");
        FileUtils.copyFile(screenShot, screenshotFile);
    }
}
